version: '3.1'
services:
  stats-server:
    ports:
      - "9090:9090"
    build: stat-service/stat-server/
    container_name: stat-service
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

#  ewm-service:
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ewm-service
#      - DB_NAME=Shareit-db
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=root
#      - DB_HOST=db
#      - DB_PORT=5432
#
#  ewm-db:
#    image: postgres:14-alpine
