FROM amazoncorretto:11-alpine-jdk
COPY target/*.jar home/root/applications/java-explore-with-me/main-service-app.jar
ENTRYPOINT ["java","-jar","/home/root/applications/java-explore-with-me/main-service-app.jar"]