CREATE TABLE PUBLIC.hits
(
    id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app  VARCHAR(100) NOT NULL,
    uri  VARCHAR(320) NOT NULL,
    ip   VARCHAR(320) NOT NULL,
    time TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
